const translations = {
    welcome_back: { en: "Welcome back", id: "Selamat datang kembali" },
    main_menu: { en: "Main Menu", id: "Menu Utama" },
    menu_attendance: { en: "Attendance", id: "Absensi" },
    check_in: { en: "Check in", id: "Absen sekarang" },
    menu_dashboard: { en: "Dashboard", id: "Dasbor" },
    statistics: { en: "Statistics", id: "Statistik" },
    menu_history: { en: "Savings", id: "Tabungan" },
    attendance_records: { en: "Track your savings", id: "Catat tabunganmu" },
    menu_my_attendance: { en: "My Attendance", id: "Absensi Saya" },
    my_personal_record: { en: "My personal record", id: "Catatan pribadi saya" },
    menu_information: { en: "Information", id: "Informasi" },
    information_links: { en: "Information & links", id: "Informasi & tautan" },
    banner_title: { en: "Keep your attendance organized.", id: "Jaga absensimu tetap rapi." },
    banner_text: { en: "Check your records and stay up to date with Attendreem.", id: "Pantau catatanmu dan tetap up to date dengan Attendreem." },
    nav_home: { en: "Home", id: "Beranda" },
    nav_attendance: { en: "Attendance", id: "Absensi" },
    nav_dashboard: { en: "Dashboard", id: "Dasbor" },
    nav_history: { en: "Savings", id: "Tabungan" },
    nav_my: { en: "My", id: "Saya" },

    page_attendance: { en: "Attendance", id: "Absensi" },
    label_date: { en: "Date", id: "Tanggal" },
    label_time: { en: "Time", id: "Waktu" },
    label_status: { en: "Status", id: "Status" },
    status_not_selected: { en: "Not selected", id: "Belum dipilih" },
    status_present: { en: "Present", id: "Hadir" },
    status_permission: { en: "Permission", id: "Izin" },
    status_sick: { en: "Sick", id: "Sakit" },
    status_absent: { en: "Absent", id: "Alpa" },
    label_reason: { en: "Reason", id: "Alasan" },
    reason_placeholder: { en: "Why are you absent?", id: "Kenapa kamu tidak hadir?" },
    label_verification: { en: "VERIFICATION", id: "VERIFIKASI" },
    btn_open_camera: { en: "Open Camera", id: "Buka Kamera" },
    btn_take_photo: { en: "Take Photo", id: "Ambil Foto" },
    face_loading: { en: "Loading face detector...", id: "Memuat pendeteksi wajah..." },
    face_detected: { en: "Face detected. You can take the photo.", id: "Wajah terdeteksi. Kamu bisa ambil foto." },
    face_not_detected: { en: "Align your face in the frame.", id: "Posisikan wajahmu di dalam bingkai." },
    face_unavailable: { en: "Face detection unavailable, you can still take a photo.", id: "Pendeteksi wajah tidak tersedia, kamu tetap bisa ambil foto." },
    face_liveness_wait: { en: "Face detected. You must blink to verify it's really you.", id: "Wajah terdeteksi. Wajib kedipkan mata dulu untuk verifikasi." },
    face_liveness_passed: { en: "Blink verified! You can take the photo.", id: "Berhasil berkedip! Kamu bisa ambil foto." },
    toast_liveness_required: { en: "You must blink first so we know it's really you, not a photo.", id: "Wajib kedipkan mata dulu supaya sistem tahu ini bukan dari foto." },
    btn_submit_attendance: { en: "Submit Attendance", id: "Kirim Absensi" },

    page_dashboard: { en: "Dashboard", id: "Dasbor" },
    overview_label: { en: "Attendance Overview", id: "Ringkasan Absensi" },
    overview_title: { en: "Your attendance summary", id: "Ringkasan absensimu" },
    overview_text: { en: "Keep your attendance consistent and stay on track.", id: "Jaga konsistensi absensimu dan tetap pada jalurnya." },
    total_attendance: { en: "Total Attendance", id: "Total Absensi" },
    label_total_savings: { en: "Total Savings", id: "Total Tabungan" },
    status_hadir_label: { en: "Hadir", id: "Hadir" },
    status_izin_label: { en: "Izin", id: "Izin" },
    status_sakit_label: { en: "Sakit", id: "Sakit" },
    status_alpa_label: { en: "Alpa", id: "Alpa" },
    attendance_label: { en: "ATTENDANCE", id: "ABSENSI" },
    attendance_calendar: { en: "Attendance Calendar", id: "Kalender Absensi" },
    activity_label: { en: "ACTIVITY", id: "AKTIVITAS" },
    recent_attendance: { en: "Recent Attendance", id: "Absensi Terbaru" },
    view_all: { en: "View All", id: "Lihat Semua" },
    show_less: { en: "Show Less", id: "Tampilkan Lebih Sedikit" },
    no_attendance_yet: { en: "No attendance data yet.", id: "Belum ada data absensi." },
    statistics_label: { en: "STATISTICS", id: "STATISTIK" },
    attendance_statistics: { en: "Attendance Statistics", id: "Statistik Absensi" },
    attendance_rate: { en: "Attendance Rate", id: "Tingkat Kehadiran" },
    stat_total: { en: "Total", id: "Total" },
    stat_present: { en: "Present", id: "Hadir" },
    stat_absent: { en: "Absent", id: "Tidak Hadir" },
    insight_label: { en: "ATTENDANCE INSIGHT", id: "WAWASAN ABSENSI" },
    ready_label: { en: "READY?", id: "SIAP?" },
    quick_action_title: { en: "Take your attendance today", id: "Catat absensimu hari ini" },
    quick_action_text: { en: "Don't forget to record your attendance.", id: "Jangan lupa catat absensimu." },
    quick_action_btn: { en: "Attendance →", id: "Absensi →" },

    page_history: { en: "Savings", id: "Tabungan" },
    label_month: { en: "MONTH", id: "BULAN" },
    label_status_filter: { en: "STATUS", id: "STATUS" },
    all_months: { en: "All Months", id: "Semua Bulan" },
    all_status: { en: "All Status", id: "Semua Status" },
    no_history_title: { en: "No attendance history", id: "Belum ada riwayat absensi" },
    no_history_text: { en: "Your attendance records will appear here.", id: "Catatan absensimu akan muncul di sini." },
    checkin_at: { en: "Check-in at", id: "Absen masuk pukul" },

    tab_school_savings: { en: "School", id: "Sekolah" },
    tab_personal_savings: { en: "Personal", id: "Pribadi" },
    label_personal_balance: { en: "PERSONAL SAVINGS BALANCE", id: "SALDO TABUNGAN PRIBADI" },
    label_add_personal_hint: { en: "Track your own savings", id: "Catat tabunganmu sendiri" },
    label_savings_balance: { en: "SAVINGS BALANCE", id: "SALDO TABUNGAN" },
    label_savings_history: { en: "TRANSACTION HISTORY", id: "RIWAYAT TRANSAKSI" },
    label_type_filter: { en: "TYPE", id: "JENIS" },
    all_types: { en: "All Transactions", id: "Semua Transaksi" },
    type_setor: { en: "Deposit", id: "Setor" },
    type_tarik: { en: "Withdrawal", id: "Tarik" },
    no_savings_title: { en: "No savings yet", id: "Belum ada tabungan" },
    no_savings_text: { en: "Your savings transactions will appear here.", id: "Transaksi tabunganmu akan muncul di sini." },
    label_total_deposit: { en: "Total Deposit", id: "Total Setor" },
    label_total_withdraw: { en: "Total Withdrawal", id: "Total Tarik" },

    page_manage_savings: { en: "Manage Savings", id: "Kelola Tabungan" },
    menu_manage_savings: { en: "Manage Savings", id: "Kelola Tabungan" },
    page_manage_spp: { en: "Manage SPP", id: "Kelola SPP" },
    menu_manage_spp: { en: "Manage SPP", id: "Kelola SPP" },

    menu_feedback: { en: "Suggestions & Complaints", id: "Saran & Keluhan" },
    menu_admin_feedback: { en: "Student Suggestions & Complaints", id: "Saran & Keluhan Siswa" },
    page_feedback: { en: "Suggestions & Complaints", id: "Saran & Keluhan" },
    page_admin_feedback: { en: "Student Suggestions & Complaints", id: "Saran & Keluhan Siswa" },
    label_compose_feedback: { en: "Write Something", id: "Tulis Sesuatu" },
    label_category_saran: { en: "Suggestion", id: "Saran" },
    label_category_keluhan: { en: "Complaint", id: "Keluhan" },
    placeholder_feedback_message: { en: "Write your suggestion or complaint...", id: "Tulis saran atau keluhanmu..." },
    btn_send_feedback: { en: "Send", id: "Kirim" },
    label_my_feedback: { en: "My Submissions", id: "Kiriman Saya" },
    label_all_feedback: { en: "Submissions", id: "Daftar Kiriman" },
    label_status_new: { en: "New", id: "Baru" },
    label_status_read: { en: "Read", id: "Sudah Dibaca" },
    label_filter_all: { en: "All", id: "Semua" },
    text_no_feedback_yet: { en: "No submissions yet.", id: "Belum ada kiriman." },
    toast_feedback_message_required: { en: "Please write a message first.", id: "Silakan tulis pesannya dulu." },
    toast_feedback_sent: { en: "Sent. Thank you!", id: "Terkirim. Terima kasih!" },
    toast_feedback_failed: { en: "Failed to send: ", id: "Gagal mengirim: " },
    toast_feedback_deleted: { en: "Submission deleted.", id: "Kiriman dihapus." },
    confirm_delete_feedback: { en: "Delete this submission?", id: "Hapus kiriman ini?" },
    btn_mark_read: { en: "Mark as Read", id: "Tandai Dibaca" },
    label_select_student: { en: "Select Student", id: "Pilih Siswa" },
    label_current_balance: { en: "Current Balance", id: "Saldo Saat Ini" },
    label_transaction_type: { en: "Transaction Type", id: "Jenis Transaksi" },
    label_amount: { en: "Amount (Rp)", id: "Jumlah (Rp)" },
    placeholder_amount: { en: "e.g. 10000", id: "misal: 10000" },
    label_note_optional: { en: "Note (optional)", id: "Catatan (opsional)" },
    placeholder_savings_note: { en: "e.g. Weekly savings", id: "misal: Tabungan mingguan" },
    btn_add_transaction: { en: "Add Transaction", id: "Tambah Transaksi" },
    toast_select_student_first: { en: "Please select a student first.", id: "Silakan pilih siswa dulu." },
    toast_enter_valid_amount: { en: "Please enter a valid amount.", id: "Masukkan jumlah yang valid." },
    toast_insufficient_balance: { en: "Insufficient balance for this withdrawal.", id: "Saldo tidak cukup untuk penarikan ini." },
    toast_transaction_added: { en: "Transaction added.", id: "Transaksi ditambahkan." },
    toast_transaction_failed: { en: "Failed to save transaction: ", id: "Gagal menyimpan transaksi: " },
    toast_transaction_deleted: { en: "Transaction deleted.", id: "Transaksi dihapus." },
    confirm_delete_transaction: { en: "Delete this transaction?", id: "Hapus transaksi ini?" },
    text_no_transactions_yet: { en: "No transactions yet for this student.", id: "Belum ada transaksi untuk siswa ini." },
    option_choose_student: { en: "Choose a student...", id: "Pilih siswa..." },

    tab_spp: { en: "SPP", id: "SPP" },
    label_spp_status: { en: "SPP STATUS", id: "STATUS SPP" },
    label_spp_amount: { en: "Amount", id: "Jumlah" },
    badge_spp_unpaid: { en: "Not Paid Yet", id: "Belum Bayar" },
    badge_spp_pending: { en: "Awaiting Verification", id: "Menunggu Verifikasi" },
    badge_spp_approved: { en: "Paid", id: "Lunas" },
    badge_spp_rejected: { en: "Rejected", id: "Ditolak" },
    label_submit_spp_proof: { en: "Submit Payment Proof", id: "Kirim Bukti Pembayaran" },
    label_submit_spp_hint: { en: "Upload your transfer proof for this month", id: "Upload bukti transfer SPP bulan ini" },
    btn_choose_proof: { en: "Choose Proof Photo", id: "Pilih Foto Bukti" },
    btn_proof_selected: { en: "Proof photo selected", id: "Foto bukti dipilih" },
    placeholder_spp_note: { en: "e.g. Transferred via BCA", id: "misal: Transfer lewat BCA" },
    btn_submit_proof: { en: "Submit Proof", id: "Kirim Bukti" },
    btn_submitting: { en: "Submitting...", id: "Mengirim..." },
    toast_spp_proof_required: { en: "Please choose a proof photo first.", id: "Silakan pilih foto bukti dulu." },
    toast_spp_upload_failed: { en: "Failed to upload proof: ", id: "Gagal mengupload bukti: " },
    toast_spp_submit_failed: { en: "Failed to submit: ", id: "Gagal mengirim: " },
    toast_spp_submitted: { en: "Proof submitted. Waiting for admin verification.", id: "Bukti terkirim. Menunggu verifikasi admin." },
    text_spp_pending_info: { en: "Your proof is being reviewed by the admin.", id: "Bukti kamu sedang diperiksa oleh admin." },
    text_spp_approved_info: { en: "Paid on", id: "Lunas sejak" },
    text_spp_rejected_info: { en: "Rejected: ", id: "Ditolak: " },
    text_spp_rejected_hint: { en: "Please submit a new proof.", id: "Silakan kirim ulang bukti pembayaran." },
    label_spp_history: { en: "SPP HISTORY", id: "RIWAYAT SPP" },
    no_spp_title: { en: "No SPP records yet", id: "Belum ada riwayat SPP" },
    no_spp_text: { en: "Your SPP payment records will appear here.", id: "Riwayat pembayaran SPP-mu akan muncul di sini." },

    label_spp_settings: { en: "SPP Amount Settings", id: "Pengaturan Jumlah SPP" },
    hint_spp_settings: { en: "The fixed monthly SPP amount every student needs to pay.", id: "Jumlah SPP bulanan tetap yang harus dibayar setiap siswa." },
    label_spp_monthly_amount: { en: "Monthly SPP Amount (Rp)", id: "Jumlah SPP Bulanan (Rp)" },
    btn_save_spp_amount: { en: "Save Amount", id: "Simpan Jumlah" },
    toast_spp_amount_saved: { en: "SPP amount saved.", id: "Jumlah SPP disimpan." },
    toast_enter_valid_spp_amount: { en: "Please enter a valid amount.", id: "Masukkan jumlah yang valid." },

    label_spp_per_student: { en: "Per-Student SPP Amount", id: "Jumlah SPP per Siswa" },
    hint_spp_per_student: { en: "Set a different SPP amount for a specific student, overriding the default above.", id: "Atur jumlah SPP berbeda untuk siswa tertentu, menggantikan jumlah default di atas." },
    label_spp_current_default: { en: "Using default amount: {amount}", id: "Pakai jumlah default: {amount}" },
    label_spp_current_custom: { en: "Custom amount set: {amount}", id: "Jumlah khusus terpasang: {amount}" },
    placeholder_spp_student_amount: { en: "Leave empty to use default", id: "Kosongkan untuk pakai default" },
    btn_save_spp_student_amount: { en: "Save for This Student", id: "Simpan untuk Siswa Ini" },
    btn_reset_spp_student_amount: { en: "Use Default", id: "Pakai Default" },
    toast_spp_student_amount_saved: { en: "Custom SPP amount saved for this student.", id: "Jumlah SPP khusus disimpan untuk siswa ini." },
    toast_spp_student_amount_reset: { en: "This student now uses the default amount.", id: "Siswa ini sekarang pakai jumlah default." },
    label_spp_active_overrides: { en: "Students with a custom amount", id: "Siswa dengan jumlah khusus" },
    text_no_spp_overrides: { en: "No students have a custom SPP amount yet.", id: "Belum ada siswa dengan jumlah SPP khusus." },
    btn_reset: { en: "Reset", id: "Reset" },
    label_spp_pending_review: { en: "Pending SPP Verification", id: "Verifikasi SPP Tertunda" },
    text_no_spp_pending: { en: "No submissions waiting for review.", id: "Tidak ada kiriman yang menunggu diperiksa." },
    btn_view_proof: { en: "View Proof", id: "Lihat Bukti" },
    btn_approve: { en: "Approve", id: "Setujui" },
    btn_reject: { en: "Reject", id: "Tolak" },
    prompt_reject_reason: { en: "Reason for rejecting (shown to the student):", id: "Alasan menolak (akan ditampilkan ke siswa):" },
    toast_spp_approved: { en: "Marked as paid.", id: "Ditandai sudah lunas." },
    toast_spp_rejected: { en: "Submission rejected.", id: "Kiriman ditolak." },
    toast_spp_review_failed: { en: "Failed to save review: ", id: "Gagal menyimpan review: " },
    label_spp_recent_reviews: { en: "Recently Reviewed", id: "Baru Diperiksa" },
    text_no_spp_reviews: { en: "No reviewed submissions yet.", id: "Belum ada kiriman yang diperiksa." },
    btn_delete_proof: { en: "Delete proof photo", id: "Hapus foto bukti" },
    confirm_delete_spp_proof: { en: "Delete this rejected submission and its proof photo? This cannot be undone.", id: "Hapus kiriman yang ditolak ini beserta foto buktinya? Tindakan ini tidak bisa dibatalkan." },
    toast_spp_proof_deleted: { en: "Submission and proof photo deleted.", id: "Kiriman dan foto bukti dihapus." },

    label_manage_holidays: { en: "Calendar Events", id: "Acara Kalender" },
    label_period_reset: { en: "Attendance Calculation Period", id: "Periode Perhitungan Absensi" },
    hint_period_reset: { en: "Attendance before this date is kept in history, but ignored by dashboards and auto-Alpa. Use this to restart the count for a new semester/year.", id: "Data absen sebelum tanggal ini tetap tersimpan di riwayat, tapi diabaikan di dashboard dan perhitungan auto-Alpa. Pakai ini untuk mengulang hitungan di semester/tahun ajaran baru." },
    label_period_start: { en: "Count attendance starting from", id: "Hitung absensi mulai dari" },
    label_period_end: { en: "Until (optional)", id: "Sampai (opsional)" },
    hint_period_end: { en: "Leave empty to keep counting through today with no end date.", id: "Kosongkan kalau mau terus dihitung sampai sekarang, tanpa batas akhir." },
    btn_save_period: { en: "Save Period", id: "Simpan Periode" },
    btn_preset_today: { en: "Today", id: "Hari Ini" },
    btn_preset_month: { en: "Start of This Month", id: "Awal Bulan Ini" },
    btn_preset_year: { en: "Start of This Year", id: "Awal Tahun Ini" },
    btn_preset_sem1: { en: "Semester 1 (July)", id: "Semester 1 (Juli)" },
    btn_preset_sem2: { en: "Semester 2 (January)", id: "Semester 2 (Januari)" },
    btn_preset_end_sem1: { en: "End of Semester 1 (Dec)", id: "Akhir Semester 1 (Des)" },
    btn_preset_end_sem2: { en: "End of Semester 2 (June)", id: "Akhir Semester 2 (Jun)" },
    btn_preset_no_end: { en: "No end date", id: "Tanpa Batas" },
    toast_period_saved: { en: "Attendance period saved.", id: "Periode absensi tersimpan." },
    toast_select_date_first: { en: "Please pick a date first.", id: "Silakan pilih tanggal dulu." },
    toast_end_before_start: { en: "End date can't be before the start date.", id: "Tanggal akhir tidak boleh sebelum tanggal mulai." },
    text_period_current: { en: "Currently counting:", id: "Saat ini dihitung:" },
    text_period_to: { en: "to", id: "sampai" },
    text_period_no_end: { en: "no end date", id: "tanpa batas akhir" },
    label_holiday_date: { en: "Date", id: "Tanggal" },
    label_holiday_label: { en: "Label", id: "Keterangan" },
    placeholder_holiday_label: { en: "e.g. Independence Day", id: "misal: Hari Kemerdekaan" },
    btn_add_holiday: { en: "Add Holiday", id: "Tambah Libur" },
    text_no_holidays_yet: { en: "No holidays added yet.", id: "Belum ada hari libur yang ditambahkan." },
    toast_select_date_label: { en: "Please fill in the date and label.", id: "Silakan isi tanggal dan keterangan." },
    toast_holiday_added: { en: "Holiday added.", id: "Hari libur ditambahkan." },
    toast_holiday_exists: { en: "That date is already marked as a holiday.", id: "Tanggal itu sudah ditandai sebagai libur." },
    toast_holiday_failed: { en: "Failed to save: ", id: "Gagal menyimpan: " },
    toast_holiday_deleted: { en: "Holiday deleted.", id: "Hari libur dihapus." },
    confirm_delete_holiday: { en: "Delete this holiday?", id: "Hapus hari libur ini?" },
    status_holiday: { en: "Holiday", id: "Libur" },
    label_holiday_type: { en: "Event type", id: "Jenis Acara" },
    type_holiday: { en: "Holiday", id: "Libur" },
    type_spp: { en: "SPP Payment", id: "Bayar SPP" },
    type_exam: { en: "Exam", id: "Ujian" },
    type_event: { en: "School Event", id: "Acara Sekolah" },

    page_my_attendance: { en: "My Attendance", id: "Absensi Saya" },
    score_label: { en: "ATTENDANCE SCORE", id: "SKOR ABSENSI" },
    score_no_data: { en: "No data yet", id: "Belum ada data" },
    score_excellent: { en: "Excellent consistency", id: "Konsistensi sangat baik" },
    score_good: { en: "Good consistency", id: "Konsistensi baik" },
    score_needs_improvement: { en: "Needs improvement", id: "Perlu ditingkatkan" },
    current_streak: { en: "Current Streak", id: "Rentetan Saat Ini" },
    active_days: { en: "Active Days", id: "Hari Aktif" },
    unit_days: { en: "Days", id: "Hari" },
    attendance_activity_label: { en: "ATTENDANCE ACTIVITY", id: "AKTIVITAS ABSENSI" },
    recent_activity: { en: "Recent Activity", id: "Aktivitas Terbaru" },
    no_activity_yet: { en: "No activity yet.", id: "Belum ada aktivitas." },
    monthly_overview_label: { en: "MONTHLY OVERVIEW", id: "RINGKASAN BULANAN" },
    label_today: { en: "TODAY", id: "HARI INI" },
    label_yesterday: { en: "YESTERDAY", id: "KEMARIN" },
    no_attendance_insight_title: { en: "No attendance yet", id: "Belum ada absensi" },
    no_attendance_insight_text: { en: "Start recording your attendance to see insights.", id: "Mulai catat absensimu untuk melihat wawasan." },
    great_insight_title: { en: "You're doing great!", id: "Kerja bagus!" },
    great_insight_text: { en: "Your attendance has been consistent.", id: "Absensimu sudah konsisten." },
    good_insight_title: { en: "Good attendance", id: "Absensi baik" },
    good_insight_text: { en: "Keep it up, you're doing well.", id: "Pertahankan, kamu sudah baik." },
    improve_insight_title: { en: "Keep improving", id: "Terus tingkatkan" },
    improve_insight_text: { en: "Try to attend more consistently.", id: "Coba hadir lebih konsisten." },

    tab_attendance_section: { en: "Attendance", id: "Absensi" },
    tab_development: { en: "Development", id: "Perkembangan" },
    label_grade_average: { en: "GRADE AVERAGE", id: "RATA-RATA NILAI" },
    label_grades_label: { en: "GRADES", id: "NILAI" },
    label_grades: { en: "Grades", id: "Nilai" },
    no_grades_title: { en: "No grades yet", id: "Belum ada nilai" },
    no_grades_text: { en: "Your grades will appear here once added by the school.", id: "Nilaimu akan muncul di sini setelah ditambahkan oleh sekolah." },
    label_activities_label: { en: "ACTIVITIES & NOTES", id: "AKTIVITAS & CATATAN" },
    label_activities_notes: { en: "Activities & Notes", id: "Aktivitas & Catatan" },
    no_activities_title: { en: "No activities or notes yet", id: "Belum ada aktivitas atau catatan" },
    no_activities_text: { en: "Activities, achievements and notes from your school will appear here.", id: "Kegiatan, prestasi, dan catatan dari sekolah akan muncul di sini." },
    type_kegiatan: { en: "Activity", id: "Kegiatan" },
    type_prestasi: { en: "Achievement", id: "Prestasi" },
    type_pelanggaran: { en: "Violation", id: "Pelanggaran" },
    type_catatan: { en: "Note", id: "Catatan" },

    page_manage_development: { en: "Manage Development", id: "Kelola Perkembangan" },
    menu_manage_development: { en: "Manage Student Development", id: "Kelola Perkembangan Siswa" },
    label_add_grade: { en: "Add Grade", id: "Tambah Nilai" },
    placeholder_subject: { en: "Subject (e.g. Mathematics)", id: "Mata pelajaran (misal: Matematika)" },
    placeholder_period: { en: "Period (e.g. UTS 1, Semester 1)", id: "Periode (misal: UTS 1, Semester 1)" },
    placeholder_score: { en: "Score (0-100)", id: "Nilai (0-100)" },
    placeholder_grade_note: { en: "Note (optional)", id: "Catatan (opsional)" },
    btn_add_grade: { en: "Add Grade", id: "Tambah Nilai" },
    label_add_activity: { en: "Add Activity or Note", id: "Tambah Kegiatan atau Catatan" },
    label_activity_type: { en: "Type", id: "Jenis" },
    placeholder_activity_title: { en: "Title (e.g. Won 1st place in Science Olympiad)", id: "Judul (misal: Juara 1 Olimpiade Sains)" },
    placeholder_activity_desc: { en: "Description (optional)", id: "Deskripsi (opsional)" },
    btn_add_activity: { en: "Add", id: "Tambah" },
    label_grades_history: { en: "Grades", id: "Nilai" },
    label_activities_history: { en: "Activities & Notes", id: "Aktivitas & Catatan" },
    toast_grade_added: { en: "Grade added.", id: "Nilai ditambahkan." },
    toast_grade_deleted: { en: "Grade deleted.", id: "Nilai dihapus." },
    toast_activity_added: { en: "Added.", id: "Ditambahkan." },
    toast_activity_deleted: { en: "Deleted.", id: "Dihapus." },
    confirm_delete_grade: { en: "Delete this grade?", id: "Hapus nilai ini?" },
    confirm_delete_activity: { en: "Delete this entry?", id: "Hapus catatan ini?" },
    text_no_grades_for_student: { en: "No grades yet for this student.", id: "Belum ada nilai untuk siswa ini." },
    text_no_activities_for_student: { en: "No activities or notes yet for this student.", id: "Belum ada kegiatan atau catatan untuk siswa ini." },
    toast_enter_valid_score: { en: "Please fill subject, period and a valid score.", id: "Isi mata pelajaran, periode, dan nilai yang valid." },
    toast_fill_activity_title: { en: "Please enter a title.", id: "Silakan isi judul." },

    day_sun: { en: "Sunday", id: "Minggu" },
    day_mon: { en: "Monday", id: "Senin" },
    day_tue: { en: "Tuesday", id: "Selasa" },
    day_wed: { en: "Wednesday", id: "Rabu" },
    day_thu: { en: "Thursday", id: "Kamis" },
    day_fri: { en: "Friday", id: "Jumat" },
    day_sat: { en: "Saturday", id: "Sabtu" },

    month_jan: { en: "January", id: "Januari" },
    month_feb: { en: "February", id: "Februari" },
    month_mar: { en: "March", id: "Maret" },
    month_apr: { en: "April", id: "April" },
    month_may: { en: "May", id: "Mei" },
    month_jun: { en: "June", id: "Juni" },
    month_jul: { en: "July", id: "Juli" },
    month_aug: { en: "August", id: "Agustus" },
    month_sep: { en: "September", id: "September" },
    month_oct: { en: "October", id: "Oktober" },
    month_nov: { en: "November", id: "November" },
    month_dec: { en: "December", id: "Desember" },

    page_settings: { en: "Settings", id: "Pengaturan" },
    label_account_info: { en: "Account Info", id: "Info Akun" },
    menu_change_password: { en: "Change Password", id: "Ubah Kata Sandi" },
    label_dark_mode: { en: "Dark Mode", id: "Mode Gelap" },
    label_language: { en: "Language", id: "Bahasa" },
    menu_about: { en: "About Attendreem", id: "Tentang Attendreem" },
    page_about: { en: "About Attendreem", id: "Tentang Attendreem" },
    about_tagline: { en: "Attendance & student management for schools", id: "Manajemen absensi & kesiswaan untuk sekolah" },
    about_description: { en: "Attendreem helps schools track daily attendance, SPP payments, savings, duty rosters, and student development — all in one simple app for students, teachers and admins.", id: "Attendreem membantu sekolah memantau absensi harian, pembayaran SPP, tabungan, jadwal piket, dan perkembangan siswa — semua dalam satu aplikasi sederhana untuk siswa, guru, dan admin." },
    label_app_version: { en: "Version", id: "Versi" },
    menu_manage_students: { en: "Manage Students", id: "Kelola Siswa" },
    menu_manage_attendance: { en: "Manage Attendance", id: "Kelola Absensi" },
    menu_send_notification: { en: "Send Notification", id: "Kirim Notifikasi" },
    menu_manage_schedule: { en: "Manage Schedule", id: "Kelola Jadwal" },
    btn_logout: { en: "Logout", id: "Keluar" },
    label_admin: { en: "Admin", id: "Admin" },

    notifications_title: { en: "Notifications", id: "Notifikasi" },
    no_new_notifications: { en: "No new notifications.", id: "Belum ada notifikasi." },
    notif_attendance_recorded: { en: "Your attendance was recorded as", id: "Absensimu tercatat sebagai" },
    notif_attendance_updated: { en: "Your attendance was updated to", id: "Absensimu diperbarui menjadi" },
    notif_broadcast_prefix: { en: "Announcement:", id: "Pengumuman:" },

    page_change_password: { en: "Change Password", id: "Ubah Kata Sandi" },
    label_new_password: { en: "New Password", id: "Kata Sandi Baru" },
    placeholder_new_password: { en: "At least 6 characters", id: "Minimal 6 karakter" },
    label_confirm_new_password: { en: "Confirm New Password", id: "Konfirmasi Kata Sandi Baru" },
    placeholder_confirm_password: { en: "Repeat new password", id: "Ulangi kata sandi baru" },
    btn_save_new_password: { en: "Save New Password", id: "Simpan Kata Sandi Baru" },
    btn_saving: { en: "Saving...", id: "Menyimpan..." },
    toast_password_min_length: { en: "Password must be at least 6 characters.", id: "Kata sandi minimal 6 karakter." },
    toast_password_mismatch: { en: "Passwords do not match.", id: "Kata sandi tidak cocok." },
    toast_password_update_failed: { en: "Failed to update password: ", id: "Gagal memperbarui kata sandi: " },
    toast_password_update_success: { en: "Password updated successfully.", id: "Kata sandi berhasil diperbarui." },

    page_manage_students: { en: "Manage Students", id: "Kelola Siswa" },
    label_add_new_student: { en: "Add New Student", id: "Tambah Siswa Baru" },
    placeholder_full_name: { en: "Full name", id: "Nama lengkap" },
    placeholder_class_major: { en: "Class / Major (e.g. XII IPA 1)", id: "Kelas / Jurusan (misal: XII IPA 1)" },
    placeholder_nis: { en: "NIS / NIM", id: "NIS / NIM" },
    placeholder_email_login: { en: "Email (for login)", id: "Email (untuk login)" },
    placeholder_password_login: { en: "Password (for login)", id: "Kata sandi (untuk login)" },
    btn_add_student: { en: "Add Student", id: "Tambah Siswa" },
    btn_adding: { en: "Adding...", id: "Menambahkan..." },
    label_student_list: { en: "Student List", id: "Daftar Siswa" },
    text_no_students_yet: { en: "No students added yet.", id: "Belum ada siswa yang ditambahkan." },
    btn_edit: { en: "Edit", id: "Ubah" },
    btn_delete: { en: "Delete", id: "Hapus" },
    btn_save: { en: "Save", id: "Simpan" },
    btn_cancel: { en: "Cancel", id: "Batal" },
    alert_admin_only: { en: "This page is for admins only.", id: "Halaman ini khusus untuk admin." },
    toast_name_email_password_required: { en: "Name, email, and password are required.", id: "Nama, email, dan kata sandi wajib diisi." },
    toast_nis_used: { en: "That NIS/NIM is already used by another student.", id: "NIS/NIM itu sudah dipakai siswa lain." },
    toast_create_account_failed: { en: "Failed to create account: ", id: "Gagal membuat akun: " },
    toast_save_profile_failed: { en: "Account created, but saving profile failed: ", id: "Akun dibuat, tapi gagal menyimpan profil: " },
    toast_student_added: { en: "Student added.", id: "Siswa ditambahkan." },
    toast_name_required: { en: "Name is required.", id: "Nama wajib diisi." },
    toast_save_failed: { en: "Failed to save: ", id: "Gagal menyimpan: " },
    toast_student_updated: { en: "Student updated.", id: "Siswa diperbarui." },
    confirm_delete_student: { en: "Delete {name}? This removes their profile and class/attendance link. Their login account will still exist in Supabase Auth and should be removed there too if needed.", id: "Hapus {name}? Ini akan menghapus profil dan data kelas/absensinya. Akun login mereka tetap ada di Supabase Auth dan sebaiknya dihapus juga di sana jika perlu." },
    toast_delete_failed: { en: "Failed to delete: ", id: "Gagal menghapus: " },
    toast_student_deleted: { en: "Student deleted.", id: "Siswa dihapus." },
    fallback_this_student: { en: "this student", id: "siswa ini" },

    badge_inactive: { en: "Inactive", id: "Non-aktif" },
    btn_mark_left: { en: "Mark Left", id: "Tandai Keluar" },
    btn_reactivate: { en: "Reactivate", id: "Aktifkan Lagi" },
    label_leave_date: { en: "Leave date", id: "Tanggal keluar" },
    hint_mark_left: { en: "Marks this student as no longer attending. Their login will be blocked and auto-absence stops counting after the leave date, but their attendance history stays intact.", id: "Menandai siswa ini sudah tidak sekolah di sini. Login mereka akan diblokir dan alpa otomatis berhenti dihitung setelah tanggal keluar, tapi riwayat absensinya tetap tersimpan." },
    toast_select_leave_date: { en: "Please select a leave date.", id: "Silakan pilih tanggal keluar." },
    toast_student_marked_left: { en: "Student marked as left/graduated.", id: "Siswa ditandai sudah keluar/lulus." },
    toast_student_reactivated: { en: "Student reactivated.", id: "Siswa diaktifkan lagi." },
    confirm_reactivate_student: { en: "Reactivate {name}? They will be able to log in again.", id: "Aktifkan lagi {name}? Mereka akan bisa login lagi." },
    text_left_on: { en: "Left on", id: "Keluar sejak" },
    login_blocked_inactive: { en: "This account is no longer active. Please contact your admin.", id: "Akun ini sudah tidak aktif. Silakan hubungi admin." },

    page_manage_attendance: { en: "Manage Attendance", id: "Kelola Absensi" },
    label_today_attendance: { en: "Today's Attendance", id: "Absensi Hari Ini" },
    btn_remind_missing_attendance: { en: "Remind Who's Missing", id: "Ingatkan yang Belum Absen" },
    toast_reminder_failed: { en: "Failed to send reminders: ", id: "Gagal mengirim pengingat: " },
    toast_nobody_to_remind: { en: "Everyone has checked in today.", id: "Semua siswa sudah absen hari ini." },
    toast_reminder_sent: { en: "Reminder sent to {count} student(s).", id: "Pengingat terkirim ke {count} siswa." },
    text_attendance_reminder_message: { en: "Reminder: you haven't checked in your attendance today. Please check in as soon as possible.", id: "Pengingat: kamu belum absen hari ini. Segera lakukan absensi ya." },
    btn_remind_missing_spp: { en: "Remind Who Hasn't Paid", id: "Ingatkan yang Belum Bayar" },
    text_spp_reminder_message: { en: "Reminder: you haven't submitted your SPP payment proof for this month. Please submit it as soon as possible.", id: "Pengingat: kamu belum mengirim bukti pembayaran SPP bulan ini. Segera kirim ya." },
    label_filter_records: { en: "Filter Records", id: "Filter Catatan" },
    label_attendance_trend: { en: "Attendance Trend (Last 14 Days)", id: "Tren Kehadiran (14 Hari Terakhir)" },
    trend_legend_good: { en: "90%+", id: "90%+" },
    trend_legend_ok: { en: "75-89%", id: "75-89%" },
    trend_legend_low: { en: "<75%", id: "<75%" },
    option_all_classes: { en: "All Classes", id: "Semua Kelas" },
    btn_export_csv: { en: "Export to CSV", id: "Ekspor ke CSV" },
    label_add_correct_attendance: { en: "Add or Correct Attendance", id: "Tambah atau Koreksi Absensi" },
    option_select_student: { en: "Select student...", id: "Pilih siswa..." },
    placeholder_reason_optional: { en: "Reason (optional for Present)", id: "Alasan (opsional untuk Hadir)" },
    btn_save_attendance: { en: "Save Attendance", id: "Simpan Absensi" },
    text_not_checked_in: { en: "Not checked in yet", id: "Belum absen" },
    text_no_students: { en: "No students yet.", id: "Belum ada siswa." },
    text_failed_to_load: { en: "Failed to load.", id: "Gagal memuat." },
    text_no_records_filter: { en: "No records for this filter.", id: "Tidak ada catatan untuk filter ini." },
    toast_no_records_export: { en: "No records to export for this filter.", id: "Tidak ada catatan untuk diekspor pada filter ini." },
    toast_csv_exported: { en: "CSV exported.", id: "CSV berhasil diekspor." },
    toast_select_student_date: { en: "Please select a student and a date.", id: "Silakan pilih siswa dan tanggal." },
    toast_save_record_failed: { en: "Failed to save: ", id: "Gagal menyimpan: " },
    toast_attendance_corrected: { en: "Attendance corrected.", id: "Absensi dikoreksi." },
    toast_attendance_added: { en: "Attendance added.", id: "Absensi ditambahkan." },

    page_send_notification: { en: "Send Notification", id: "Kirim Notifikasi" },
    label_compose_notification: { en: "Compose Notification", id: "Tulis Notifikasi" },
    placeholder_notification_message: { en: "Write your announcement...", id: "Tulis pengumumanmu..." },
    label_notification_target: { en: "Send To", id: "Kirim Ke" },
    option_target_all: { en: "All Members", id: "Semua Anggota" },
    option_target_class: { en: "Specific Class", id: "Kelas Tertentu" },
    option_target_student: { en: "Specific Student", id: "Siswa Tertentu" },
    option_select_class: { en: "Select class...", id: "Pilih kelas..." },
    btn_send_notification: { en: "Send Notification", id: "Kirim Notifikasi" },
    btn_sending: { en: "Sending...", id: "Mengirim..." },
    toast_notification_message_required: { en: "Please write a message.", id: "Silakan tulis pesan." },
    toast_notification_target_required: { en: "Please select a target.", id: "Silakan pilih target." },
    toast_notification_sent: { en: "Notification sent.", id: "Notifikasi terkirim." },
    toast_notification_failed: { en: "Failed to send: ", id: "Gagal mengirim: " },
    label_recent_broadcasts: { en: "Recently Sent", id: "Baru Dikirim" },
    text_no_broadcasts_yet: { en: "No notifications sent yet.", id: "Belum ada notifikasi yang dikirim." },
    target_label_all: { en: "All Members", id: "Semua Anggota" },

    page_manage_schedule: { en: "Manage Attendance Schedule", id: "Kelola Jadwal Absen" },
    label_schedule_class: { en: "Class", id: "Kelas" },
    option_choose_class: { en: "Choose a class...", id: "Pilih kelas..." },
    label_active_days: { en: "Active Days", id: "Hari Aktif" },
    label_start_time: { en: "Opens At", id: "Dibuka Jam" },
    label_end_time: { en: "Closes At", id: "Ditutup Jam" },
    label_late_mode: { en: "If Outside Schedule", id: "Jika Di Luar Jadwal" },
    option_mode_block: { en: "Block check-in", id: "Blokir absen" },
    option_mode_late: { en: "Allow, mark as late", id: "Tetap bisa, tandai telat" },
    btn_save_schedule: { en: "Save Schedule", id: "Simpan Jadwal" },
    toast_schedule_saved: { en: "Schedule saved.", id: "Jadwal disimpan." },
    toast_schedule_failed: { en: "Failed to save schedule: ", id: "Gagal menyimpan jadwal: " },
    toast_select_class_first: { en: "Please select a class first.", id: "Silakan pilih kelas dulu." },
    toast_select_one_day: { en: "Please select at least one active day.", id: "Pilih minimal satu hari aktif." },
    label_existing_schedules: { en: "Configured Schedules", id: "Jadwal yang Sudah Diatur" },
    text_no_schedules_yet: { en: "No schedules configured yet.", id: "Belum ada jadwal yang diatur." },
    confirm_delete_schedule: { en: "Delete the schedule for {class}?", id: "Hapus jadwal untuk {class}?" },
    toast_schedule_deleted: { en: "Schedule deleted.", id: "Jadwal dihapus." },
    toast_schedule_delete_failed: { en: "Failed to delete: ", id: "Gagal menghapus: " },
    label_mode_block_short: { en: "Block", id: "Blokir" },
    label_mode_late_short: { en: "Mark late", id: "Tandai telat" },
    toast_schedule_not_open_yet: { en: "Attendance hasn't opened yet. It opens at", id: "Absen belum dibuka. Dibuka jam" },
    toast_schedule_closed: { en: "Attendance is closed for today. It closed at", id: "Absen sudah ditutup untuk hari ini. Tutup jam" },
    toast_schedule_day_inactive: { en: "Attendance is not scheduled for today.", id: "Hari ini bukan jadwal absen." },
    toast_schedule_late_notice: { en: "You checked in outside the schedule, marked as late.", id: "Kamu absen di luar jadwal, dicatat sebagai telat." },
    label_late_until: { en: "Late Until (optional)", id: "Telat Sampai (opsional)" },
    hint_late_until: { en: "After this time, attendance is fully closed. Leave empty to close right after Closes At.", id: "Setelah jam ini, absen ditutup total. Kosongkan untuk langsung menutup absen setelah Jam Tutup." },
    toast_schedule_late_closed: { en: "Attendance is fully closed now. The late window has ended.", id: "Absen sudah ditutup total. Batas waktu telat sudah lewat." },
    label_late_window_short: { en: "late until", id: "telat sampai" },

    /* ===== PIKET ===== */
    menu_piket: { en: "Duty Roster", id: "Piket" },
    piket_subtitle: { en: "Cleaning duty schedule", id: "Jadwal piket kebersihan" },
    page_piket: { en: "Duty Roster", id: "Piket" },
    page_manage_piket: { en: "Manage Duty Roster", id: "Atur Jadwal Piket" },
    menu_manage_piket: { en: "Manage Duty Roster", id: "Atur Jadwal Piket" },
    label_piket_today: { en: "Today's Duty", id: "Piket Hari Ini" },
    label_piket_class: { en: "Class", id: "Kelas" },
    label_piket_day: { en: "Day", id: "Hari" },
    label_piket_students: { en: "Students on Duty", id: "Siswa yang Piket" },
    btn_save_piket: { en: "Save Duty Roster", id: "Simpan Jadwal Piket" },
    btn_mark_done: { en: "Mark as Done", id: "Tandai Sudah Piket" },
    btn_marking_done: { en: "Saving...", id: "Menyimpan..." },
    label_piket_status_done: { en: "Done", id: "Sudah piket" },
    label_piket_status_pending: { en: "Not done yet", id: "Belum piket" },
    label_piket_done_by: { en: "Marked done by", id: "Ditandai oleh" },
    text_piket_no_duty_today: { en: "No one is scheduled for duty today.", id: "Tidak ada jadwal piket untuk hari ini." },
    text_piket_no_class: { en: "Your profile has no class assigned yet. Contact your admin.", id: "Profil kamu belum punya kelas. Hubungi admin." },
    text_no_piket_yet: { en: "No duty roster set for this class yet.", id: "Belum ada jadwal piket untuk kelas ini." },
    toast_piket_select_class_day: { en: "Please select a class and a day.", id: "Pilih kelas dan hari dulu." },
    toast_piket_select_student: { en: "Please select at least one student.", id: "Pilih minimal satu siswa." },
    toast_piket_saved: { en: "Duty roster saved.", id: "Jadwal piket disimpan." },
    toast_piket_save_failed: { en: "Failed to save duty roster: ", id: "Gagal menyimpan jadwal piket: " },
    toast_piket_marked_done: { en: "Marked as done. Thanks!", id: "Ditandai sudah piket. Terima kasih!" },
    toast_piket_mark_failed: { en: "Failed to mark as done: ", id: "Gagal menandai piket: " },
    toast_piket_not_assigned: { en: "You're not scheduled for duty today.", id: "Kamu tidak terjadwal piket hari ini." },
    confirm_delete_piket: { en: "Delete the duty roster for {class} on {day}?", id: "Hapus jadwal piket {class} hari {day}?" },
    toast_piket_deleted: { en: "Duty roster deleted.", id: "Jadwal piket dihapus." },
    label_piket_weekly: { en: "Weekly Schedule", id: "Jadwal Mingguan" },
    label_piket_no_students_day: { en: "No one assigned", id: "Belum ada yang ditugaskan" },
    label_you: { en: "You", id: "Kamu" },
    label_piket_photo_proof: { en: "Cleaning proof photo", id: "Foto bukti kebersihan" },
    btn_take_photo: { en: "Take Photo", id: "Ambil Foto" },
    btn_photo_selected: { en: "Photo selected", id: "Foto terpilih" },
    toast_piket_photo_required: { en: "Please take a photo as proof before marking done.", id: "Ambil foto bukti dulu sebelum menandai sudah piket." },
    toast_piket_photo_upload_failed: { en: "Failed to upload photo: ", id: "Gagal mengunggah foto: " },
    btn_change_photo: { en: "Change Photo", id: "Ganti Foto" },
    label_piket_photos_submitted: { en: "Proof photos submitted", id: "Foto bukti yang terkumpul" },
    toast_piket_photo_updated: { en: "Photo updated. Thanks!", id: "Foto berhasil diganti. Terima kasih!" },

    btn_scan_piket: { en: "📷 Scan Duty Paper", id: "📷 Scan Kertas Piket" },
    text_scanning_piket: { en: "Reading photo...", id: "Membaca foto..." },
    toast_scan_select_class_day: { en: "Please choose a class and day first before scanning.", id: "Pilih kelas dan hari dulu sebelum scan." },
    toast_scan_matched: { en: "{matched} of {total} names recognized automatically. Please review the checkboxes below before saving.", id: "{matched} dari {total} nama berhasil dikenali otomatis. Cek kembali daftar di bawah sebelum simpan." },
    toast_scan_no_match: { en: "No matching names were detected in the photo. Try a clearer photo or check the boxes manually.", id: "Tidak ada nama yang cocok terdeteksi dari foto. Coba foto yang lebih jelas atau centang manual." },
    toast_scan_failed: { en: "Failed to read the photo: ", id: "Gagal membaca foto: " },
    label_scan_hint: { en: "Take a clear, well-lit photo of the duty list. You can still fix anything manually below.", id: "Foto kertas piket dengan jelas dan terang. Kamu tetap bisa koreksi manual di bawah." },

    page_information: { en: "Information", id: "Informasi" },
    page_admin_information: { en: "Manage Information", id: "Kelola Informasi" },
    menu_manage_information: { en: "Manage Information", id: "Kelola Informasi" },
    label_compose_info: { en: "Add Information", id: "Tambah Informasi" },
    label_all_info: { en: "Information", id: "Informasi" },
    label_category_pengumuman: { en: "School Announcement", id: "Pengumuman Sekolah" },
    label_category_jadwal: { en: "Class Schedule", id: "Jadwal Pelajaran" },
    label_category_lainnya: { en: "Other", id: "Lainnya" },
    placeholder_info_title: { en: "Title", id: "Judul" },
    placeholder_info_body: { en: "Details...", id: "Detail..." },
    btn_publish_info: { en: "Publish", id: "Terbitkan" },
    btn_publishing: { en: "Publishing...", id: "Menerbitkan..." },
    text_no_info_yet: { en: "No information posted yet.", id: "Belum ada informasi." },
    toast_info_title_required: { en: "Please enter a title.", id: "Masukkan judul dulu." },
    toast_info_body_required: { en: "Please enter the details.", id: "Masukkan detail informasinya dulu." },
    toast_info_published: { en: "Information published.", id: "Informasi diterbitkan." },
    toast_info_failed: { en: "Failed to save: ", id: "Gagal menyimpan: " },
    confirm_delete_info: { en: "Delete this information?", id: "Hapus informasi ini?" },
    toast_info_deleted: { en: "Information deleted.", id: "Informasi dihapus." },

    page_manage_parents: { en: "Manage Parent Accounts", id: "Kelola Akun Orang Tua" },
    menu_manage_parents: { en: "Manage Parent Accounts", id: "Kelola Akun Orang Tua" },
    label_add_new_parent: { en: "Add New Parent Account", id: "Tambah Akun Orang Tua Baru" },
    btn_add_parent: { en: "Add Parent Account", id: "Tambah Akun Orang Tua" },
    label_parent_accounts: { en: "Parent Accounts", id: "Akun Orang Tua" },
    option_choose_parent: { en: "Choose a parent account...", id: "Pilih akun orang tua..." },
    text_no_parents_yet: { en: "No parent accounts yet.", id: "Belum ada akun orang tua." },
    text_no_children_linked: { en: "No children linked", id: "Belum ada anak yang ditautkan" },
    label_linked_students: { en: "Linked Students", id: "Siswa Tertaut" },
    hint_linked_students: { en: "This parent can view these students' attendance, SPP, and development (read-only).", id: "Orang tua ini dapat melihat absensi, SPP, dan perkembangan siswa ini (hanya lihat)." },
    btn_link_student: { en: "Link", id: "Tautkan" },
    btn_unlink: { en: "Unlink", id: "Lepas Tautan" },
    toast_parent_created: { en: "Parent account created.", id: "Akun orang tua berhasil dibuat." },
    toast_link_added: { en: "Student linked.", id: "Siswa berhasil ditautkan." },
    toast_link_removed: { en: "Link removed.", id: "Tautan berhasil dilepas." },
    confirm_unlink_student: { en: "Unlink this student from this parent account?", id: "Lepas tautan siswa ini dari akun orang tua ini?" },
    page_parent_portal: { en: "Parent Portal", id: "Portal Orang Tua" },
    label_select_child: { en: "Viewing", id: "Melihat" },
    no_children_title: { en: "No students linked yet", id: "Belum ada siswa yang ditautkan" },
    no_children_text: { en: "Ask the school admin to link your account to your child's student profile.", id: "Minta admin sekolah untuk menautkan akunmu ke profil anakmu." },

    label_bulk_import: { en: "Bulk Import (CSV)", id: "Impor Massal (CSV)" },
    hint_bulk_import: { en: "Upload a CSV file with columns: name, class, nis, email, password.", id: "Unggah file CSV dengan kolom: name, class, nis, email, password." },
    btn_download_template: { en: "Download Template", id: "Unduh Template" },
    btn_import: { en: "Import", id: "Impor" },
    btn_importing: { en: "Importing {current}/{total}...", id: "Mengimpor {current}/{total}..." },
    toast_choose_csv_file: { en: "Please choose a CSV file first.", id: "Pilih file CSV dulu." },
    toast_csv_empty: { en: "The CSV file is empty.", id: "File CSV kosong." },
    toast_csv_missing_columns: { en: "CSV must have at least name, email, and password columns.", id: "CSV harus punya minimal kolom name, email, dan password." },
    toast_bulk_import_done: { en: "Import finished: {success}/{total} students added.", id: "Impor selesai: {success}/{total} siswa berhasil ditambahkan." },
    label_failed_rows: { en: "Failed rows", id: "Baris yang gagal" },

    page_manage_teachers: { en: "Manage Teachers", id: "Kelola Guru" },
    menu_manage_teachers: { en: "Manage Teachers", id: "Kelola Guru" },
    label_add_new_teacher: { en: "Add New Teacher Account", id: "Tambah Akun Guru Baru" },
    btn_add_teacher: { en: "Add Teacher Account", id: "Tambah Akun Guru" },
    label_teacher_accounts: { en: "Teacher Accounts", id: "Akun Guru" },
    option_choose_class: { en: "Choose a class...", id: "Pilih kelas..." },
    text_no_teachers_yet: { en: "No teacher accounts yet.", id: "Belum ada akun guru." },
    label_class_assigned: { en: "Class", id: "Kelas" },
    toast_choose_class_first: { en: "Please choose a class first.", id: "Pilih kelas dulu." },
    toast_teacher_class_saved: { en: "Teacher's class updated.", id: "Kelas guru berhasil diperbarui." },
    toast_teacher_fields_required: { en: "Please fill in name, class, email, and password.", id: "Isi nama, kelas, email, dan password dulu." },
    toast_teacher_created: { en: "Teacher account created.", id: "Akun guru berhasil dibuat." },
    confirm_delete_teacher: { en: "Delete teacher account {name}?", id: "Hapus akun guru {name}?" },
    toast_teacher_deleted: { en: "Teacher account deleted.", id: "Akun guru berhasil dihapus." },
    page_teacher_dashboard: { en: "Teacher Dashboard", id: "Dasbor Guru" },
    label_todays_attendance: { en: "Today's Attendance", id: "Absensi Hari Ini" },
    text_no_students_in_class: { en: "No students in this class yet.", id: "Belum ada siswa di kelas ini." },
    toast_select_status: { en: "Please select a status first.", id: "Pilih status dulu." },
    toast_attendance_saved: { en: "Attendance saved.", id: "Absensi berhasil disimpan." },

    btn_change_photo: { en: "Change Photo", id: "Ubah Foto" },
    toast_photo_upload_failed: { en: "Failed to upload photo: ", id: "Gagal mengunggah foto: " },
    toast_photo_updated: { en: "Profile photo updated.", id: "Foto profil berhasil diperbarui." },

    page_leave_request: { en: "Leave Request", id: "Pengajuan Izin" },
    menu_leave_request: { en: "Submit a Leave Request", id: "Ajukan Izin / Cuti" },
    label_submit_leave_request: { en: "Submit Leave Request", id: "Ajukan Izin" },
    hint_leave_request: { en: "Submit this ahead of time for a future absence. Your admin will review and approve it.", id: "Ajukan ini sebelum hari-H untuk ketidakhadiran di masa depan. Admin akan meninjau dan menyetujuinya." },
    label_leave_type: { en: "Type", id: "Jenis" },
    label_start_date: { en: "Start Date", id: "Tanggal Mulai" },
    label_end_date: { en: "End Date", id: "Tanggal Selesai" },
    placeholder_leave_reason: { en: "Reason", id: "Alasan" },
    btn_submit_leave_request: { en: "Submit Request", id: "Ajukan" },
    label_my_leave_requests: { en: "My Leave Requests", id: "Pengajuan Izin Saya" },
    text_no_leave_requests: { en: "No leave requests yet.", id: "Belum ada pengajuan izin." },
    toast_invalid_date_range: { en: "End date must not be before start date.", id: "Tanggal selesai tidak boleh sebelum tanggal mulai." },
    toast_leave_request_submitted: { en: "Leave request submitted.", id: "Pengajuan izin berhasil dikirim." },
    badge_leave_pending: { en: "Pending", id: "Menunggu" },
    badge_leave_approved: { en: "Approved", id: "Disetujui" },
    badge_leave_rejected: { en: "Rejected", id: "Ditolak" },
    page_manage_leave: { en: "Leave Requests", id: "Pengajuan Izin" },
    menu_manage_leave: { en: "Leave Requests", id: "Pengajuan Izin" },
    label_pending_leave_requests: { en: "Pending Requests", id: "Menunggu Persetujuan" },
    label_reviewed_leave_requests: { en: "Reviewed", id: "Sudah Ditinjau" },
    text_no_pending_leave: { en: "No pending leave requests.", id: "Tidak ada pengajuan yang menunggu." },
    text_no_reviewed_leave: { en: "No reviewed leave requests yet.", id: "Belum ada pengajuan yang ditinjau." },
    btn_approve: { en: "Approve", id: "Setujui" },
    btn_reject: { en: "Reject", id: "Tolak" },
    toast_leave_approved: { en: "Leave request approved.", id: "Pengajuan izin disetujui." },
    toast_leave_rejected: { en: "Leave request rejected.", id: "Pengajuan izin ditolak." },

    page_audit_log: { en: "Audit Log", id: "Log Audit" },
    menu_audit_log: { en: "Audit Log", id: "Log Audit" },
    hint_audit_log: { en: "Tracks grade changes, SPP verification decisions, student status changes, and account deletions. Most recent first.", id: "Mencatat perubahan nilai, keputusan verifikasi SPP, perubahan status siswa, dan penghapusan akun. Terbaru di atas." },
    option_all_tables: { en: "All", id: "Semua" },
    text_no_audit_entries: { en: "No audit entries yet.", id: "Belum ada catatan audit." }
};

const dayKeys = ["day_sun", "day_mon", "day_tue", "day_wed", "day_thu", "day_fri", "day_sat"];
const monthKeys = ["month_jan", "month_feb", "month_mar", "month_apr", "month_may", "month_jun", "month_jul", "month_aug", "month_sep", "month_oct", "month_nov", "month_dec"];

function dayNameOf(dateStr) {
    if (!dateStr) return "";
    const parts = String(dateStr).split("-");
    if (parts.length < 3) return "";
    const d = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
    if (isNaN(d.getTime())) return "";
    const entry = translations[dayKeys[d.getDay()]];
    return entry ? entry[getLang()] : "";
}

function monthNameOf(monthIndex) {
    const entry = translations[monthKeys[monthIndex]];
    return entry ? entry[getLang()] : "";
}

function dayMonthLabel(date) {
    return date.getDate() + " " + monthNameOf(date.getMonth());
}

function dayMonthYearLabel(date) {
    return String(date.getDate()).padStart(2, "0") + " " + monthNameOf(date.getMonth()) + " " + date.getFullYear();
}

function monthYearLabel(date) {
    return monthNameOf(date.getMonth()) + " " + date.getFullYear();
}

function dateKey(date) {
    return date.getFullYear() + "-" + String(date.getMonth() + 1).padStart(2, "0") + "-" + String(date.getDate()).padStart(2, "0");
}

function formatRupiah(amount) {
    const n = Number(amount) || 0;
    return "Rp" + n.toLocaleString("id-ID");
}

function getLang() {
    return localStorage.getItem("attendly-lang") || "en";
}

function setLang(lang) {
    localStorage.setItem("attendly-lang", lang);
    applyLang();
}

function applyLang() {
    const lang = getLang();

    document.querySelectorAll("[data-i18n]").forEach(function (el) {
        const entry = translations[el.getAttribute("data-i18n")];
        if (entry && entry[lang]) {
            el.textContent = entry[lang];
        }
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
        const entry = translations[el.getAttribute("data-i18n-placeholder")];
        if (entry && entry[lang]) {
            el.placeholder = entry[lang];
        }
    });
}

document.addEventListener("DOMContentLoaded", applyLang);
